controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
app_reservation_admin_pdf:
    path: /admin/reservations/pdf
    controller: App\Controller\ReservationAdminController::generateAllReservationsPdf
